env:
  global:
    - secure: "Px8iT5Bw+zbiFdy5sQij7uMtKLMgCP7gHu5tPhnsxwZJ4CP0h7zR7UPlQa3Pa3t1UxAw7z/EQoflz68U56cLrwwgfMfls5aaH4el/rC57tk/AjST9bb2Pmj/TknX3BUiVmcXfaiq+57/CDI94EMZDbhd1p+e9I7bbCHyBnAVOW4="
    - secure: "PBXgLoYtREMx542NX4zVaYBpSoVhkdwLdJbsoP9xejfUiSRwgvpe/Vl1sGH1WtSOfpcmkWOz+cR9ngnvfGYJJXk//UNuQXoxpWs2lzI7Pqip5y/ZOGGh7+aQ64NMOif5h8NyZktn4+8jfe6kt3RNE+7mjo+sqPhq38QgB9lhG84="
env:
  global:
    - secure: Zg+5iwJnVny4piSbj0ED8RXimPSrFZwVR+tgOtN+sWNqb72Ge0KmyPJysZnouSsj1hX6irdN/qJIqONZ50n6pMVh81g5HL95zoUz4dwnIYW+4fRTLjh1sh4zh+VjQ0SAY+EhpG70bd+xdsYUcyQXCK6Y25pZgTNmKOpvWNZs/JA=
    - secure: dsytZ+46ggv2NlZx+MSruy8MlD6OE0mQrZ7sUqENpw7VJTKfuNFWhNK8sQb7q0udkuBFyzVaUrol8MfqdCHevl8MxeXBCZynK9rX9YQfw5KJCyFrruRzabl6tyeNcGr9YkeM4xvFHC+hJ7201ddSirpSl6XcEz3S11aim7mx5xw=

language: node_js
node_js: "0.10"
install:
  - npm -g install bower
  - npm -g install grunt-cli
  - npm install
  - yes | bower install
  - cd node_modules/intern
  - npm install
  - cd ../..
script:
  - grunt jshint
  - grunt intern:node
  - if [[ "$TRAVIS_SECURE_ENV_VARS" == "true" ]]; then grunt intern:remote; fi
